name: Deploy EasyLookDOC to Azure Web App

on:
  push:
    branches:
      - main  # Triggera il deploy quando fai push su main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout del codice
      uses: actions/checkout@v3

    - name: Configura Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Installazione dipendenze
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy su Azure Web App
      uses: azure/webapps-deploy@v2
      with:
        app-name: easylookdoc  # <-- usa il nome esatto della tua Web App
        slot-name: Production
        publish-profile: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}
        package: .